/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controllers.UserController;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.User;
import thread.TinhToan;

/**
 *
 * @author truon
 */
public class ManageUser extends javax.swing.JFrame {

    private static final Object lock = new Object();
    private int id = -1;
    Thread thread1;
    Thread thread2;
    Thread thread3;
    Thread thread4;
    Thread thread5;

    /**
     * Creates new form ManageUser
     */
    public ManageUser() {
        initComponents();
        showTable("select * from user");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtJob = new javax.swing.JTextField();
        jbtnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUser = new javax.swing.JTable();
        jBtnUpdate = new javax.swing.JButton();
        btnFormTinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Email");

        jLabel2.setText("Password");

        jLabel3.setText("Name");

        jLabel4.setText("Age");

        jLabel5.setText("Address");

        jLabel6.setText("Job");

        jbtnCreate.setText("Tạo người dùng");
        jbtnCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnCreateMouseClicked(evt);
            }
        });

        jtbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Password", "Name", "Age", "Address", "Job"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbUser);

        jBtnUpdate.setText("Chinh sua");
        jBtnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnUpdateMouseClicked(evt);
            }
        });

        btnFormTinh.setText("Form tính (DEMO Thread)");
        btnFormTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtJob, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jbtnCreate)
                .addGap(44, 44, 44)
                .addComponent(jBtnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnFormTinh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCreate)
                    .addComponent(jBtnUpdate)
                    .addComponent(btnFormTinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showTable(String query) {
        thread1 = new Thread(() -> {
            synchronized (lock) {
                if (thread1.isAlive()) {
                    System.out.println("Thread 1 đang chạy");
                } else {
                    System.out.println("Thread 1 đã dừng");
                }
                DefaultTableModel model = (DefaultTableModel) this.jtbUser.getModel();
                model.setRowCount(0);
                try {
                    UserController userController = new UserController();
                    ResultSet users = userController.getAllUser(query);
                    while (users.next()) {
                        int id = users.getInt("id");
                        String email = users.getString("email");
                        String password = users.getString("password");
                        String name = users.getString("name");
                        int age = users.getInt("age");
                        String adress = users.getString("address");
                        String job = users.getString("job");

                        Object[] dataTable = {id, email, password, name, age, adress, job};
                        DefaultTableModel table = (DefaultTableModel) this.jtbUser.getModel();
                        table.addRow(dataTable);
                    }
                } catch (Exception e) {
                    System.out.println("Error" + e);
                }
                lock.notify();
            }
        });
        thread1.start();

    }

    private void jbtnCreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCreateMouseClicked
        // TODO add your handling code here:
        thread2 = new Thread(() -> {
            synchronized (lock) {

                String email = jtxtEmail.getText();
                String password = jtxtPassword.getText();
                String name = jtxtName.getText();
                String age = jtxtAge.getText();
                String address = jtxtAddress.getText();
                String job = jtxtJob.getText();
                if (email.isEmpty() || password.isEmpty() || name.isEmpty() || age.isEmpty() || address.isEmpty() || job.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Nhap day du cac truong!");
                    return;
                }
                User user = new User(email, password, name, Integer.parseInt(age), address, job);
                try {

                    UserController userController = new UserController();
                    userController.createUser(user, this);
                    showTable("select * from user");
                } catch (Exception e) {
                    System.out.println("Err: " + e);
                }
            }
        });
        thread2.start();

    }//GEN-LAST:event_jbtnCreateMouseClicked

    private void jtbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbUserMouseClicked
        // TODO add your handling code here:
        int row = jtbUser.rowAtPoint(evt.getPoint());
        Object[] options = {"Sửa", "Xóa"};
        int choice = JOptionPane.showOptionDialog(null, "Bạn muốn sửa hay xóa?", "Lựa chọn", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (choice == JOptionPane.YES_OPTION) {
            thread3 = new Thread(() -> {
                synchronized (lock) {
                    int idTable = Integer.parseInt(this.jtbUser.getModel().getValueAt(row, 0).toString());
                    this.id = idTable;
                    String email = this.jtbUser.getModel().getValueAt(row, 1).toString();
                    String password = this.jtbUser.getModel().getValueAt(row, 2).toString();
                    String name = this.jtbUser.getModel().getValueAt(row, 3).toString();
                    int age = Integer.parseInt(this.jtbUser.getModel().getValueAt(row, 4).toString());
                    String adress = this.jtbUser.getModel().getValueAt(row, 5).toString();
                    String job = this.jtbUser.getModel().getValueAt(row, 6).toString();

                    jtxtEmail.setText(email);
                    jtxtPassword.setText(password);
                    jtxtName.setText(name);
                    jtxtAge.setText("" + age);
                    jtxtAddress.setText(adress);
                    jtxtJob.setText(job);

                }
            });
            thread3.start();

        } else if (choice == JOptionPane.NO_OPTION) {
            thread4 = new Thread(() -> {
                synchronized (lock) {
                    int idTable = Integer.parseInt(this.jtbUser.getModel().getValueAt(row, 0).toString());
                    UserController userController = new UserController();
                    userController.deleteUser(idTable, this);
                    showTable("select * from user");

                }
            });
            thread4.start();

        }


    }//GEN-LAST:event_jtbUserMouseClicked

    private void jBtnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnUpdateMouseClicked
        // TODO add your handling code here:
        thread5 = new Thread(() -> {
            synchronized (lock) {
                String email = jtxtEmail.getText();
                String password = jtxtPassword.getText();
                String name = jtxtName.getText();
                String age = jtxtAge.getText();
                String address = jtxtAddress.getText();
                String job = jtxtJob.getText();

                if (email.isEmpty() || password.isEmpty() || name.isEmpty() || age.isEmpty() || address.isEmpty() || job.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Nhap day du cac truong!");
                    return;
                }
                User user = new User(id, email, password, name, Integer.parseInt(age), address, job);
                UserController userController = new UserController();
                userController.updateUser(user, this);
                this.id = -1;
                showTable("select * from user");

            }
        });
        thread5.start();

    }//GEN-LAST:event_jBtnUpdateMouseClicked

    private void btnFormTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormTinhActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TinhToan tt = new TinhToan();
        tt.setVisible(true);
    }//GEN-LAST:event_btnFormTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormTinh;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCreate;
    private javax.swing.JTable jtbUser;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtAge;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtJob;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPassword;
    // End of variables declaration//GEN-END:variables
}
